# Generated by Django 4.2.29 on 2026-03-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_material_filefield'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['created_at'], name='idx_activity_created_at'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='idx_category_name'),
        ),
    ]
