# Generated by Django 4.2.29 on 2026-04-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_add_activity_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='preview_pdf',
            field=models.FileField(blank=True, help_text='Optional PDF shown inline on the activity page. Use when File is Word/Office so faculty see a preview here and download the editable file.', null=True, upload_to='materials/previews/%Y/%m/', verbose_name='Preview (PDF)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, help_text='Main file for download (e.g. Word). PDFs can use this field alone for preview + download.', null=True, upload_to='materials/%Y/%m/'),
        ),
    ]
